graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

voyager:
    mapping: /voyager
    enabled: true
    pageTitle: Voyager